import type { TransactionType } from "../schemas/dataSchema";

export const transactionList: TransactionType[] = [
  {
    id: 1,
    "business-unit": "Custo de vida",
    category: "Moradia",
    subcategory: "Aluguel",
    bank: "Banco Santander S.A.",
    type: "saidas",
    operation: "PIX",
    description: "Pagamento do aluguel de outubro",
    amount: 2000,
    currency: "BRL",
    date: "2025-10-01T10:30:00Z",
  },
  {
    id: 2,
    "business-unit": "Custo de vida",
    category: "Moradia",
    subcategory: "Água",
    bank: "Nu Pagamentos S.A.",
    type: "saidas",
    operation: "Débito",
    description: "Conta de água referente a setembro",
    amount: 120,
    currency: "BRL",
    date: "2025-09-15T12:00:00Z",
  },
  {
    id: 3,
    "business-unit": "Custo de vida",
    category: "Moradia",
    subcategory: "Luz",
    bank: "Caixa Econômica Federal",
    type: "saidas",
    operation: "Boleto bancário",
    description: "Pagamento da conta de energia elétrica",
    amount: 210,
    currency: "BRL",
    date: "2025-09-20T09:00:00Z",
  },
  {
    id: 4,
    "business-unit": "Custo de vida",
    category: "Transporte",
    subcategory: "Gasolina",
    bank: "Banco Santander S.A.",
    type: "saidas",
    operation: "Débito",
    description: "Abastecimento do carro",
    amount: 250,
    currency: "BRL",
    date: "2025-09-10T14:00:00Z",
  },
  {
    id: 5,
    "business-unit": "Custo de vida",
    category: "Transporte",
    subcategory: "Pedágio",
    bank: "Nu Pagamentos S.A.",
    type: "saidas",
    operation: "Crédito",
    description: "Despesa com pedágios em viagem",
    amount: 35,
    currency: "BRL",
    date: "2025-09-05T11:00:00Z",
  },
  {
    id: 6,
    "business-unit": "Custo de vida",
    category: "Transporte",
    subcategory: "Combustível",
    bank: "Caixa Econômica Federal",
    type: "saidas",
    operation: "PIX",
    description: "Abastecimento de moto",
    amount: 50,
    currency: "BRL",
    date: "2025-08-28T08:30:00Z",
  },
  {
    id: 7,
    "business-unit": "Custo de vida",
    category: "Alimentação",
    subcategory: "Mercado",
    bank: "Banco Santander S.A.",
    type: "saidas",
    operation: "Débito",
    description: "Compras de supermercado do mês",
    amount: 600,
    currency: "BRL",
    date: "2025-08-15T18:00:00Z",
  },
  {
    id: 8,
    "business-unit": "Custo de vida",
    category: "Alimentação",
    subcategory: "Restaurante",
    bank: "Nu Pagamentos S.A.",
    type: "saidas",
    operation: "Crédito",
    description: "Jantar em restaurante",
    amount: 150,
    currency: "BRL",
    date: "2025-08-12T20:00:00Z",
  },
  {
    id: 9,
    "business-unit": "Custo de vida",
    category: "Alimentação",
    subcategory: "Delivery",
    bank: "Caixa Econômica Federal",
    type: "saidas",
    operation: "PIX",
    description: "Pedido de delivery de pizza",
    amount: 90,
    currency: "BRL",
    date: "2025-08-01T21:00:00Z",
  },
  {
    id: 10,
    "business-unit": "Negócios",
    category: "Receitas",
    subcategory: "Serviços de programação",
    bank: "Banco Santander S.A.",
    type: "entradas",
    operation: "Transferência",
    description: "Recebimento por projeto de desenvolvimento web",
    amount: 8000,
    currency: "BRL",
    date: "2025-07-20T10:00:00Z",
  },
  {
    id: 11,
    "business-unit": "Negócios",
    category: "Receitas",
    subcategory: "Serviços de consultoria",
    bank: "Nu Pagamentos S.A.",
    type: "entradas",
    operation: "PIX",
    description: "Receita por consultoria estratégica",
    amount: 5000,
    currency: "BRL",
    date: "2025-07-18T15:00:00Z",
  },
  {
    id: 12,
    "business-unit": "Negócios",
    category: "Custos",
    subcategory: "Assinatura de software operacional",
    bank: "Caixa Econômica Federal",
    type: "saidas",
    operation: "Crédito",
    description: "Pagamento mensal de ferramenta de CRM",
    amount: 300,
    currency: "BRL",
    date: "2025-07-10T09:00:00Z",
  },
  {
    id: 13,
    "business-unit": "Negócios",
    category: "Custos",
    subcategory: "Infraestrutura de TI",
    bank: "Banco Santander S.A.",
    type: "saidas",
    operation: "PIX",
    description: "Pagamento de servidor em nuvem",
    amount: 1200,
    currency: "BRL",
    date: "2025-06-25T16:00:00Z",
  },
  {
    id: 14,
    "business-unit": "Negócios",
    category: "Despesas",
    subcategory: "Marketing",
    bank: "Nu Pagamentos S.A.",
    type: "saidas",
    operation: "Transferência",
    description: "Campanha de anúncios online",
    amount: 2500,
    currency: "BRL",
    date: "2025-06-15T11:30:00Z",
  },
  {
    id: 15,
    "business-unit": "Negócios",
    category: "Despesas",
    subcategory: "Assinaturas administrativas",
    bank: "Caixa Econômica Federal",
    type: "saidas",
    operation: "Boleto bancário",
    description: "Assinatura de serviços contábeis",
    amount: 400,
    currency: "BRL",
    date: "2025-06-05T13:00:00Z",
  },
];
